stages:
  - pre-check
  - build
  - test


include:
  - component: "gitlab.com/sequoia-pgp/common-ci/sequoia-pipeline@main"
    inputs:
      extra_args: "-- --skip leak_tests"

fuzzing:
  image: jampot.sequoia-pgp.org/sequoia-pgp/build-docker-image/trixie-prebuild
  stage: pre-check
  before_script:
    - !reference [.before_script, defaults]
  script:
    - cargo check --manifest-path openpgp/Cargo.toml --no-default-features --features crypto-fuzzing,compression,allow-experimental-crypto,allow-variable-time-crypto
    - if ! git diff --quiet Cargo.lock ; then echo "Cargo.lock changed.  Please add the change to the corresponding commit." ; git diff ; false ; fi
    - if ! git diff --quiet ; then echo "The build changed the source.  Please investigate." ; git diff ; fi
  after_script:
    - !reference [.after_script, end]
  rules:
    - !reference [.default_rules, rules]

doc:
  image: jampot.sequoia-pgp.org/sequoia-pgp/build-docker-image/trixie-prebuild
  stage: build
  before_script:
    - !reference [.before_script, defaults]
  script:
    - cargo doc --document-private-items --no-deps
  after_script:
    - !reference [.after_script, end]
  rules:
    - !reference [.default_rules, rules]
